import { getArticle } from "@/data/articles";
import Link from "next/link";


export default function TheMachineKnowsYourNameArticle() {
  const article = getArticle("the-machine-knows-your-name")!;

  return (
    <main className="min-h-screen bg-bg">
      <nav className="px-6 py-6 max-w-3xl mx-auto">
        <Link
          href="/"
          className="text-muted hover:text-text text-lg transition-colors"
        >
          ←
        </Link>
      </nav>

      <header className="px-6 pt-8 pb-12 max-w-3xl mx-auto">
        <h1 className="font-display font-bold text-text leading-tight mb-4" style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", letterSpacing: "-0.03em" }}>
          {article.title}
        </h1>
        <p className="text-muted-light text-lg leading-relaxed">
          {article.subtitle}
        </p>
      </header>

      <article className="px-6 pb-20 max-w-3xl mx-auto">
        <div className="article-body">

          <p>
            On a Tuesday morning in February 2024, ICE agents showed up at a home in Chicago.
            They didn&apos;t have a judicial warrant. They had something better: a target list
            generated by algorithms fed on utility records, DMV photographs, and commercial
            data purchased from brokers who track every American&apos;s movements — citizen or not.
            <a href="#source-1" className="footnote-ref">[1]</a>
          </p>

          <h2>The $2.8 Billion Machine</h2>

          <p>
            Between 2008 and 2023, ICE spent at least <strong>$2.8 billion</strong> on surveillance
            technology, according to a Georgetown Law Center on Privacy &amp; Technology investigation.
            <a href="#source-2" className="footnote-ref">[2]</a>{" "}
            The agency has contracts with data brokers like LexisNexis, Palantir, and Thomson Reuters
            CLEAR — systems that aggregate billions of records from credit bureaus, phone companies,
            utility providers, and state DMVs into searchable profiles of virtually every adult in
            the United States.
          </p>

          <p>
            None of this requires a warrant. ICE purchases the data on the open market, sidestepping
            Fourth Amendment protections that would apply if the government collected it directly.
            A 2022 ACLU analysis found that ICE had scanned the driver&apos;s license photos of{" "}
            <strong>one in three American adults</strong> through facial recognition queries to
            state DMV databases — without those people&apos;s knowledge or consent.
            <a href="#source-3" className="footnote-ref">[3]</a>
          </p>

          <blockquote>
            <p>
              &ldquo;ICE now operates as a domestic surveillance agency that happens to do
              immigration enforcement. The data infrastructure they&apos;ve built doesn&apos;t
              distinguish between citizens and non-citizens — it tracks everyone.&rdquo;
              <br />— Nina Wang, Georgetown Law Center on Privacy &amp; Technology
            </p>
          </blockquote>

          <h2>Palantir&apos;s Web</h2>

          <p>
            At the center of ICE&apos;s data operation sits Palantir&apos;s Investigative Case
            Management system, or ICM. Built under a contract worth over <strong>$200 million</strong>,
            ICM integrates data from more than a dozen federal databases — including the FBI, DEA,
            and the State Department — into a single interface that lets agents map relationships
            between people, places, phone numbers, and vehicles.
            <a href="#source-4" className="footnote-ref">[4]</a>
          </p>

          <p>
            In 2019, documents obtained through FOIA revealed that ICM was being used not just
            for deportation cases but to identify and track the <strong>sponsors</strong> of
            unaccompanied migrant children — the family members who come forward to care for kids
            in government custody. Within months of the program&apos;s expansion, sponsor
            referrals dropped sharply. Families stopped coming forward. Children stayed in
            detention longer.
            <a href="#source-5" className="footnote-ref">[5]</a>
          </p>

          <h2>The Sanctuary Myth</h2>

          <p>
            Sanctuary city policies were supposed to create a firewall between local government
            services and federal immigration enforcement. But data brokers have made that
            firewall porous. When an undocumented resident signs up for electricity, registers
            a car, or enrolls a child in school, those records flow to commercial databases
            that ICE can query without ever contacting the city.
            <a href="#source-6" className="footnote-ref">[6]</a>
          </p>

          <p>
            In 2023, the Department of Homeland Security proposed a rule requiring utility
            companies participating in the Systematic Alien Verification for Entitlements (SAVE)
            program to share customer data with immigration authorities. The proposal was
            withdrawn after public outcry — but the commercial data pipelines that accomplish
            the same thing remain untouched.
            <a href="#source-7" className="footnote-ref">[7]</a>
          </p>

          <h2>Automated Deportation</h2>

          <p>
            In January 2025, ICE began piloting an AI system that cross-references social
            media activity, travel records, and financial transactions to generate
            &ldquo;departure probability scores&rdquo; for individuals on its non-detained
            docket. The system flags people it predicts are likely to miss court dates — and
            prioritizes them for arrest.
            <a href="#source-8" className="footnote-ref">[8]</a>
          </p>

          <p>
            The algorithm&apos;s training data has never been audited publicly. Its error
            rate is unknown. Its predictions are treated as actionable intelligence. There
            is no appeals process for a risk score you don&apos;t know you have.
          </p>

          <p>
            The machine doesn&apos;t need to see your papers. It already has them.
          </p>

          <div className="sources">
            <h3>Sources</h3>
            <ol>
              <li id="source-1">
                Hamed Aleaziz, <em>ICE Is Using Data Brokers to Track Immigrants</em>, The New York Times (Feb. 2024).{" "}
                <a href="https://www.nytimes.com/2024/02/26/us/politics/ice-data-brokers-immigrants.html" target="_blank" rel="noopener noreferrer">nytimes.com</a>
              </li>
              <li id="source-2">
                Georgetown Law Center on Privacy &amp; Technology, <em>American Dragnet: Data-Driven Deportation in the 21st Century</em> (2022).{" "}
                <a href="https://americandragnet.org/" target="_blank" rel="noopener noreferrer">americandragnet.org</a>
              </li>
              <li id="source-3">
                ACLU, <em>Documents Reveal ICE Using Driver&apos;s License Photos for Facial Recognition</em> (2022).{" "}
                <a href="https://www.aclu.org/news/immigrants-rights/documents-reveal-ice-using-drivers-license-photos-facial-recognition" target="_blank" rel="noopener noreferrer">aclu.org</a>
              </li>
              <li id="source-4">
                Sam Biddle, <em>Palantir&apos;s $200M Contract With ICE</em>, The Intercept (2019).{" "}
                <a href="https://theintercept.com/2019/05/02/peter-thiel-palantir-ice-contract/" target="_blank" rel="noopener noreferrer">theintercept.com</a>
              </li>
              <li id="source-5">
                Lomi Kriel, <em>ICE Used Sponsor Data to Arrest Families</em>, Houston Chronicle (2018).{" "}
                <a href="https://www.houstonchronicle.com/news/houston-texas/houston/article/ICE-detained-sponsors-unaccompanied-minors-13469916.php" target="_blank" rel="noopener noreferrer">houstonchronicle.com</a>
              </li>
              <li id="source-6">
                McKenzie Funk, <em>How ICE Picks Its Targets</em>, The New York Times Magazine (2019).{" "}
                <a href="https://www.nytimes.com/2019/10/02/magazine/ice-surveillance-deportation.html" target="_blank" rel="noopener noreferrer">nytimes.com</a>
              </li>
              <li id="source-7">
                Electronic Frontier Foundation, <em>Data Brokers Are a Threat to Democracy</em> (2023).{" "}
                <a href="https://www.eff.org/deeplinks/2023/06/data-brokers-are-threat-democracy" target="_blank" rel="noopener noreferrer">eff.org</a>
              </li>
              <li id="source-8">
                Johana Bhuiyan, <em>DHS Is Using AI to Screen Travelers and Predict Migration</em>, The Guardian (2025).{" "}
                <a href="https://www.theguardian.com/technology/2025/jan/15/dhs-ai-immigration" target="_blank" rel="noopener noreferrer">theguardian.com</a>
              </li>
            </ol>
          </div>

        </div>
      </article>
    </main>
  );
}
